### ISSUE TITLE
Mac QSS

### ISSUE THREAD

**Issue by maifeeulasad** [GTRONICK/QSS#3]
Hello sir,
We are developing a project, where we are already using your beautiful [QSS](https://github.com/maifeeulasad/Joss-Paint/tree/8c391f2d2ecd9b1013a9c33af10157f1be33309b/sources).

And I must tell that, everyone is obsessed with Mac's look and feel. Can you bring that look with `.qss` ? We will surely love to use that.

Thanks in advance. And I must tell you that, these are some great qss.

https://github.com/maifeeulasad/Joss-Paint/issues/37

**Comment by GTRONICK** [comment]
Hey! I hope you are doing well.

Sure! I just need some references, like screenshots and such of the Mac's
look and feel you need. I don't have a Mac PC, and I have noticed that
depending on the version it changes a little. Coul you provide some images
and screenshots?

Thanks!

**Comment by maifeeulasad** [comment]
Hey,
So far so good. What about you ?

Can you try make them like these : 
![combined](https://user-images.githubusercontent.com/29339330/102715275-7e1eb480-42fe-11eb-9b77-4bbcb8c1e1aa.jpeg)

And these : 
![combined3](https://user-images.githubusercontent.com/29339330/102715287-94c50b80-42fe-11eb-9cb7-13ea8344b6b8.png)

If you make a design combing these two, I think it will be really nice.

I downloaded this from Google, I have no copyright over these images.

It'll be really awesome to have these awesome `qss`

**Comment by GTRONICK** [comment]
Working on it! ;)

**Comment by maifeeulasad** [comment]
That's great. I can't express, how excited I'm. Thanks.

**Comment by GTRONICK** [comment]
I have finally uploaded the new Theme! I hope you enjoy it!. [MacOS Theme](https://github.com/GTRONICK/QSS/blob/master/MacOS.qss)

Any suggestion is welcome! (or donation XD)

**Comment by maifeeulasad** [comment]
hey looks really cool, i saw your readme, but can you tell me why this is not being applied here : https://github.com/maifeeulasad/Joss-Paint/tree/feature/crop

**Comment by GTRONICK** [comment]
What do you mean? Please elaborate on the description of your problem with
details  ;)
