### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by alpinebuster** [GTRONICK/QSS#7]
Hi, could you provide `go-up-symbolic.symbolic.png` `go-down-symbolic.symbolic.png` `object-select-symbolic.symbolic.png` `go-previous-symbolic.symbolic.png` `go-next-symbolic.symbolic.png` file, it seems to be missing in MacOS.qss ?

**Comment by GTRONICK** [comment]
Yeah, these files are included in all major Linux desktops, you can see the paths in the file. I will add them however

**Comment by xakod** [comment]
@GTRONICK not all use linux : )

**Comment by GTRONICK** [comment]
You Should! hahaha, please be patient, I have been too busy, I will add the images as soon as I can. Meanwhile, you can use any transparent .png custom image, and replace its path in the qss file. So you can have your own customized checks for example.

**Comment by GTRONICK** [comment]
Added the files and updated the readme. You can find the images in the QSS_IMG folder
