### ISSUE TITLE
Wrong hex color in MacOS.qss?

### ISSUE THREAD

**Issue by mdrost** [GTRONICK/QSS#9]
Hi, honestly I have no idea how MacOS should look, but when I use style from MacOS.qss I get message `QCssParser::parseHexColor: Unknown color name '#ffff'`. I believe the problem is here:
```
QComboBox:editable, QComboBox:!editable, QComboBox::drop-down:editable, QComboBox:!editable:on, QComboBox::drop-down:editable:on {
    background: #ffff;
}
```
When I change `background: #ffff;` to `background: #ffffff;` message disappears, but I am not 100% sure it's the color that should be there :P

**Comment by GTRONICK** [comment]
Thanks a lot!, Fixed.
